### ISSUE TITLE
How about removing brackets of calling functions?

### ISSUE THREAD

**Issue by tiye** [DAddYE/igo#10] opened 2014-03-31 02:27 UTC
Hi, I love your project. I made my attempt too before, by stupidly adding curly brackets by counting indentations. And here is it: https://github.com/Cirru/goose .

I didn't learn the skills of parsing the whole language. Also, I'm still wondering about how it would be if we remove some more brackets from Go's syntax, like Ruby, in which `f(a, b)` can be write like `f a, b`.

May I ask your opinion about it?

**Comment by DAddYE** [comment] 2014-03-31 06:57
I spent a little bit of time thinking about it but then I figured out that for a `c` like language is better be `consistent`, and `golang` is very `consistent` in his syntax, so I want to keep it as our rule as well.

Anyway I think for some constructs like: 

```
example.each() do (a, b int): a * b
```

we can allow to work without:

```
example.each do (a, b int): a * b
```

Since the `do` make it clear that is a `call`. Anyway isn't immediate since I need to improve the `look back`.

**Comment by tiye** [comment] 2014-03-31 07:38
Actually I like CoffeeScript's strategy better, where `f(x, y)` can be `f x, y` but brackets in `f()` can not be removed.

I noticed in the demo, there is a:

``` coffee
# `do` notation for functions as last parameter
x := strings.TrimFunc("_hello_") do (r rune) bool
    return r == '_'
```

Following CoffeeScript's solution, it can be like:

``` coffee
x := strings.TrimFunc "_hello_", (r rune) bool
    return r == '_'
```

While putting last parameter out of the brackets makes it confusing to me.

**Comment by vendethiel** [comment] 2014-03-31 07:39
This was rejected in #7. I'd really like to avoid opening this can of worms ...

**Comment by tiye** [comment] 2014-03-31 07:48
@Nami-Doc Yes, I agree it's messy too.
But there is a case, when functions are passed as parameters, the code becomes strange.

```
func *Person.say(txt string): fmt.Println(txt) # or not ...
```

And meanwhile I consider CoffeeScript's solution is nice.

**Comment by DAddYE** [comment] 2014-03-31 19:19
@jiyinyiyong you are right but the same could apply to `struct{}{}`, as @Nami-Doc well said that's kind of worm especially on unfinished expressions:

```
func1(a, b).
   func2(c, d).
   func3(e, f)
```

it may introduce unexpected behaviors very hard to track.

**Comment by vendethiel** [comment] 2014-03-31 19:22
I've been there. I'm a CoffeeScript (and LiveScript) team member and I've been working with other langs such as Ruby et al, and really, really nothing good comes from that.

**Comment by DAddYE** [comment] 2014-03-31 19:23
Things that I trust, and so let's close this.

**Closed as completed by DAddYE** 2014-03-31 19:23 UTC

**Comment by tiye** [comment] 2014-04-01 01:44
OK, I'm convinced.

**Comment by tiye** [comment] 2014-04-11 04:42
@Nami-Doc Might be out of topic, but as I see, indentation-based syntax is much more consistant(well, when not being mixed with curly brackets).
Would you mind taking a look on the syntax I chose and implemented?
http://cirru.org/
https://github.com/Cirru/cirru-parser#syntax

**Comment by vendethiel** [comment] 2014-04-11 06:01
Haskell-like function call (juxtaposition operator) is fine for me, since you can't go overboard with it
